/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_user_music_open_cv_Activity */

#ifndef _Included_com_example_user_music_open_cv_Activity
#define _Included_com_example_user_music_open_cv_Activity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_user_music_open_cv_Activity_PERMISSIONS_REQUEST_CODE
#define com_example_user_music_open_cv_Activity_PERMISSIONS_REQUEST_CODE 1000L
/*
 * Class:     com_example_user_music_open_cv_Activity
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_example_user_music_open_1cv_1Activity_ConvertRGBtoGray
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
